SQL고득점Kit/SELECT/나영/조건에부합하는중고거래댓글조회하기.sql

- 아무 생각 없이 LEFT 조인 사용 => 왼쪽 테이블의 모든 행이 유지되므로 댓글이 없는 경우에도 출력됨
- 두 테이블의 교집합만 반환하는 INNER JOIN을 써야 했다(이 때 테이블 순서는 상관없다)
- DATE_FORMAT()으로 날짜 형식 맞춰서 출력하기
- %Y : 연도(4자리)
- %m : 월(2자리 숫자, 01~12)
- %d : 일(2자리 숫자, 01~31)
- %M : 월 이름(영문, January 등)
- %D : 일(day) 뒤에 영어 서수 붙임 (1st, 2nd 등)

Solved: PG_조건에부합하는중고거래댓글조회하기 김나영

---

SQL고득점Kit/SELECT/지우/과일로 만든 아이스크림 고르기.sql

- 간단한 문제
- 3000보다 많다고 했으니 = 표시 안하는거 1초 고민

Solved: PG_과일로 만든 아이스크림 고르기 홍지우

---

SQL고득점Kit/SELECT/지우/평균 일일 대여 요금 구하기.sql

- AVG 집계함수를 써서 group by가 떠오름
- 여기서는 GROUP BY 종류별로 따로 평균을 내는게 아니라 필요 없음
- 첫번째 자리에서 반올림 => **`ROUND(avg(컬럼명), 0)`** 
- 0이다 0! 첫번째 자리에서 반올림한 '결과' 보기

Solved: PG_평균 일일 대여 요금 구하기 홍지우

---

SQL고득점Kit/SELECT/지우/강원도에 위치한 생산공장 목록 출력하기.sql

- substr, left 두 가지 방식으로 맨 앞 세글자 '강원도'를 골라냄
- 또 다른 방법으로는
- **`WHERE address LIKE '강원도%'`**

Solved: PG_강원도에 위치한 생산공장 목록 출력하기 홍지우

---

SQL고득점Kit/SELECT/지우/12세 이하인 여자 환자 목록 출력하기.sql

- `IFNULL(컬럼명, "Null 대체할 값")` 함수 사용함 
- 가능한 다른 방법
- `COALESCE(tlno, 'NONE')`
-  `CASE WHEN tlno IS NULL THEN 'NONE' ELSE tlno END AS tlno`

Solved: PG_12세 이하인 여자 환자 목록 출력하기 홍지우

---

SQL고득점Kit/SELECT/지우/업그레이드 된 아이템 구하기.sql

너무 어려워요..
t.parent_item_id가 RARE → RARE인 아이템들이 직접 재료로 쓰인 경우
t.item_id는 → 그 RARE 아이템으로부터 업그레이드된 아이템
출력은 i.item_id, i.item_name, i.rarity → 자식 정보
구간 | 설명
-- | --
p | parent: RARE 등급 아이템
t | item_tree: 조합 관계 (parent → child)
c | child: 업그레이드된 아이템 (= 우리가 출력하려는 대상)

Solved: PG_업그레이드 된 아이템 구하기 홍지우

---

SQL고득점Kit/SELECT/지우/어린 동물 찾기.sql

- 조건이 많아지면 `NOT IN` 사용해서 풀 수 있다. 
```
WHERE INTAKE_CONDITION NOT IN ('Aged')
```

Solved: PG_어린 동물 찾기 홍지우

---

SQL고득점Kit/SELECT/나영/업그레이드 된 아이템 구하기.sql

- 문제 제대로 보기 프로젝트 시작합니다
- 두 번 JOIN하면서 
1. ITEM_INFO 테이블과 ITEM_TREE 테이블의 ITEM_ID 매칭
2. ITEM_INFO 테이블의 'RARE'인 친구들과 ITEM_TREE 의 Parent_ITEM_ID, ITEM_ID 매칭
- 이를 통해 root가 아니면서, RARE의 자식인 행을 구할 수 있다

Solved: PG_업그레이드 된 아이템 구하기 김나영

---

SQL고득점Kit/SELECT/지우/조건에 맞는 개발자 찾기.sql

AND 연산 (&): 두 비트가 모두 1일 때만 1을 반환한다.
OR 연산 (|): 두 비트 중 하나라도 1이면 1을 반환한다.
XOR 연산 (^): 두 비트가 다르면 1, 같으면 0을 반환한다.
NOT 연산 (~): 비트를 반전시킨다.
-- 예를 들어 2진수 1010 (10)과 0110 (6)을 AND 연산하면: (겹치는 부분을 본다 - 포함하는 거에서 포함된 거 뽑을 때)
SELECT 10 & 6;  -- 결과는 2 (0010)
-- 예를 들어 2진수 1010 (10)과 0110 (6)을 OR 연산하면: (하나라도 1이면 반영한다 - 더할 때)
SELECT 10 | 6;  -- 결과는 14 (1110)

Solved: PG_조건에 맞는 개발자 찾기 홍지우

---

SQL고득점Kit/SELECT/지우/특정 물고기를 잡은 총 수 구하기.sql

- `JOIN`으로 풀어도 됐다.
- 비교
- IN (서브쿼리) | fish_type이 서브쿼리에서 추출한 리스트에 포함되는지 확인
- JOIN 방식 | 아예 두 테이블을 연결해서, 조건(fish_name)을 걸어 필터링

Solved: PG_특정 물고기를 잡은 총 수 구하기 홍지우

---

SQL고득점Kit/SELECT/지우/대장균들의 자식의 수 구하기.sql

- id(부모) = parent_id(자식의 부모) 조인 결과 
- count 썼으니까 부모 기준으로 그룹 묶고 자식 count
- 자식을! count 해야 함 (왜냐면 0도 있잖아)

Solved: PG_대장균들의 자식의 수 구하기 홍지우

---

SQL고득점Kit/JOIN/지우/조건에 맞는 도서와 저자 리스트 출력하기.sql

Solved: PG_조건에 맞는 도서와 저자 리스트 출력하기 홍지우

---

SQL고득점Kit/JOIN/지우/없어진 기록 찾기.sql

한 쪽 테이블에만 있는 걸 알고 싶다 -> LEFT/RIGHT JOIN

Solved: PG_없어진 기록 찾기 홍지우

---

SQL고득점Kit/JOIN/지우/오랜 기간 보호한 동물(1).sql

- 한 쪽 테이블만 있는 거 궁금
- JOIN 했는데 한쪽 테이블이 NULL 값인 것을 알고 싶다: LEFT JOIN + WHERE 컬럼` IS NULL`

Solved: PG_오랜 기간 보호한 동물(1) 홍지우

---

SQL고득점Kit/GROUP BY/식품분류별 가장 비싼 식품의 정보 조회하기.sql

- category는 group by로 특정 가능. price는 max() 사용으로 특정 가능. 근데 product_name은 특정 불가
-  > (category, price) 조합이랑 알맞는 product_name을 출력하기 위한 사전 작업이 필요함
- filtered 절로 저 (category, MAX_price) 조합 미리 만들어두고 <- IN 여기 안 조합인 애들 출력

Solved: PG_식품분류별 가장 비싼 식품의 정보 조회하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/즐겨찾기가 가장 많은 식당 정보 출력하기.sql

- foodType 별로 max 즐찾 수를 미리 filtered로 구한다.
- 이제 그 조합(food_type, favorites)과 일치하는 rest_id, rest_name을 IN 연산자로 골라서 출력해주면 된다.

Solved: PG_즐겨찾기가 가장 많은 식당 정보 출력하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/진료과별 총 예약 횟수 출력하기.sql

- Group by를 하면 알아서 진료코드별로 모인다. - 이 모임 안 수를  count() 해주면 끝!

Solved: PG_진료과별 총 예약 횟수 출력하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기.sql

- group by로 차 종류 묶고 + 그 안의 행 count() 
- options 속성 안에 제1정규화를 만족하지 않아 열선시트,어쩌고시트,저쩌고시트, <- 이렇게 나열되어있었음
- `options LIKE '%시트%' OR` 로 원하는 조건들 찾음

Solved: PG_자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/카테고리 별 도서 판매량 집계하기.sql

- JOIN 하고~ 
- (group by 대상, 집계 함수) 조합이니까 따로 필터링 없이 그대로 SELECT 쓰고~
- GROUP BY 위에 WHERE 절 처리해주는 문제

Solved: PG_카테고리 별 도서 판매량 집계하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/고양이와 개는 몇 마리 있을까.sql

- 타입별로 각각 몇 마리?
- 타입을 group by로 묶고 -> count 집계함수

Solved: PG_고양이와 개는 몇 마리 있을까 홍지우

---

SQL고득점Kit/GROUP BY/지우/동명 동물 수 찾기.sql

- '이름이 없는 동물은 집계에서 제외된다.'
- ➡️ WHERE 이름 IS NOT NULL
- 이게 꼭! 왜 필요할까?
- NULL, NULL 이렇게 이름에 칸을 차지하고 있다면 count >= 2 일 때 함께 표시된다. 이 경우를 제외하기 위함.!!!!!!!!!

Solved: PG_동명 동물 수 찾기 홍지우

---

SQL고득점Kit/GROUP BY/지우/입양 시각 구하기(1).sql

- 오 이 문제 올리는 거 깜빡했어여
- HOUR 사용하여 시간대별 구함
- 컬럼 BETWEEN  AND 사용

Solved: PG_입양 시각 구하기(1) 홍지우

---

SQL고득점Kit/GROUP BY/지우/가격대 별 상품 개수 구하기.sql

[풀이1]
- price / 만원 = 몫.0000000
- FLOOR(몫.000000) = 몫
- 몫 * 만원
[풀이2]
- TRUNCATE(컬럼, 숫자) 
- 양수면, (ex. TRUNCATE(3.141592, 2))
-  3.14 (뒤엔 다 버리기
- 음수면, (ex. TRUNCATE(356.141592, -2))
- 300

Solved: PG_가격대 별 상품 개수 구하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/조건에 맞는 사원 정보 조회하기.sql

- 처음에 MAX(SUM(score)) 이라는 무모한 도전을 하였지만 이건 에러유발 절대놉방법
- 미리 sum_score을 구해놓은 다음 필요한 테이블들과 JOIN 시켜둠 -
- sum_score ORDER BY DESC 순으로 나열해서 LIMIT 1로 가장 max인거 골라냄

Solved: [GROUP BY] PG_조건에 맞는 사원 정보 조회하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/연간 평가점수에 해당하는 평가 등급 및 성과금 조회하기.sql

- 상반기, 하반기 이렇게 점수가 나눠져 있는데 어떤 점수로? AVG 점수로!
-> WITH 절로 avg 점수 따로 뽑아둠
- 아예 테이블처럼 주어졌네..
- **CASE** **_`WHEN-THEN`_**  **_` ELSE`_** **END**
- 두 차례 해주어 등급, 성과금 구했다

Solved: [GROUP BY] PG_연간 평가점수에 해당하는 평가 등급 및 성과금 조회하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/부서별 평균 연봉 조회하기.sql

- 고냥 기본 group by 문제
- 소수점 첫째 자리에서 반올림 : ROUND(컬럼명,0) 해줌

Solved: [GROUP BY] PG_부서별 평균 연봉 조회하기 홍지우

---

SQL고득점Kit/GROUP BY/지우/물고기 종류 별 잡은 수 구하기.sql

- 물고기 종류별로 내야 함. group by를 fish_type으로 내려고 했더니 select에 그게 안 들어가야 하네?
- fish_type : fish_name 1:1 대응이니까 fish_name으로 group by 사용
- 질문 게시판 보니까 left join, right join 왜 결과가 다르냐고 써있던데
- 문제가 원하는 건 잡은 물고기의 수
- fish_name_info 기준 join을 하게 되면 안 잡은 물고기도 fish_name_info 에 존재하기만 하면 count | 0 으로 결과가 나올테니까 틀릴 것임

Solved: [GROUP BY] PG_물고기 종류 별 잡은 수 구하기 홍지우

---

SQL고득점Kit/String, Date/지우/자동차 평균 대여 기간 구하기.sql

- 기간: `DATEDIFF(끝 기간, 시작 기간) + 1`

Solved: [String, Date] PG_자동차 평균 대여 기간 구하기 홍지우

---

SQL고득점Kit/String, Date/지우/조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기.sql

- max view를 가진 id를 구하라!
- 풀이법1
1. max view를 구한다.
2. view 수가 maxView인 id를 구한다.
- 풀이법2
1. ORDER BY view DESC =>  LIMIT 1로 가장 먼저 오는 행  => 즉, 가장 view가 큰 행을 선택한다. 
- 그 행 안에는 MaxView를 가진 board_id가 띨롱! 있다

Solved: [String, Date] PG_조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기 홍지우

---

SQL고득점Kit/String, Date/지우/자동차 대여 기록에서 장기단기 대여 구분하기.sql

- 2022년 9월에 속하는 대여 기록: `WHERE start_date LIKE '2022-09%'`

Solved: [String, Date] PG_자동차 대여 기록에서 장기/단기 대여 구분하기 홍지우

---

SQL고득점Kit/String, Date/지우/특정 옵션이 포함된 자동차 리스트 구하기.sql

- LIKE 연산자 써서 제1정규화를 만족하지 못한 테이블 속 '%네비게이션%'을 찾았다.

Solved: [String, Date] PG_특정 옵션이 포함된 자동차 리스트 구하기 홍지우

---

SQL고득점Kit/String, Date/지우/루시와 엘라 찾기.sql

- `WHERE 이름 IN (여러, 이름, 옵션) `
- 을 활용해 여러 이름 중 하나와 일치하면 리스트에 올라가게끔 했다.

Solved: [String, Date] PG_루시와 엘라 찾기 홍지우

---

SQL고득점Kit/String, Date/나영/루시와 엘라 찾기.sql

-  IN을 사용해 특정 이름이 들어간 동물을 조회 **완**

Solved: [String, Date] PG_루시와 엘라 찾기 김나영

---

SQL고득점Kit/String, Date/나영/중성화 여부 파악하기.sql

- CASE WHEN THEN을 이용해 중성화 했는지를 확인

Solved: [String, Date] PG_중성화 여부 파악하기 김나영

---

SQL고득점Kit/String, Date/지우/DATETIME에서 DATE로 형 변환.sql

- datetime 형에서 date형으로 바꾸기 위해 `DATE_FORMAT(컬럼명, "%Y-%m-%d")`를 활용했다.

Solved: [String, Date] PG_DATETIME에서 DATE로 형 변환 홍지우

---

SQL고득점Kit/SELECT/지우/대장균의 크기에 따라 분류하기 2.sql

- 전체 결과를 n 등분 해야 한다 ->**` NTILE(n) OVER (ORDER BY 순서)`** 활용!
https://jie0025.tistory.com/85

Solved: [SELECT] PG_대장균의 크기에 따라 분류하기 2 홍지우

---

SQL고득점Kit/SELECT/지우/특정 세대의 대장균 찾기.sql

- 부모 자식이 존재하는 관계는 JOIN 을 하여 **`c.parent_id`**(자식의 부모는) = **`t.id`** (t이다) 하는 문제이다
- RECURSIVE 즉 재귀를 활용해 풀 수 있는데 
- tree의 초기값: 부모가 null 인 것이 1세대
- RECURSIVE 시작~! : tree의 초기값 기준으로 자식(여기서는 e)을 계속 더해가며 depth를 깊어지게 한다.

Solved: [SELECT] PG_특정 세대의 대장균 찾기 홍지우
